// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: room.sql

package models

import (
	"context"
	"database/sql"
)

const countRoomsByUserID = `-- name: CountRoomsByUserID :one
SELECT COUNT(*) FROM rooms
WHERE created_by = ?
`

func (q *Queries) CountRoomsByUserID(ctx context.Context, createdBy uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRoomsByUserID, createdBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRoom = `-- name: CreateRoom :execresult
INSERT INTO rooms (name, created_by) VALUES (?, ?)
`

type CreateRoomParams struct {
	Name      string `db:"name" json:"name"`
	CreatedBy uint64 `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRoom, arg.Name, arg.CreatedBy)
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms WHERE id = ?
`

func (q *Queries) DeleteRoom(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteRoom, id)
	return err
}

const getRoom = `-- name: GetRoom :one
SELECT id, name, created_by, created_at, updated_at FROM rooms WHERE id = ? LIMIT 1
`

func (q *Queries) GetRoom(ctx context.Context, id uint64) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoomsByUserID = `-- name: GetRoomsByUserID :many
SELECT id, name, created_by, created_at, updated_at FROM rooms
WHERE created_by = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetRoomsByUserIDParams struct {
	CreatedBy uint64 `db:"created_by" json:"created_by"`
	Limit     int32  `db:"limit" json:"limit"`
	Offset    int32  `db:"offset" json:"offset"`
}

func (q *Queries) GetRoomsByUserID(ctx context.Context, arg GetRoomsByUserIDParams) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, getRoomsByUserID, arg.CreatedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT id, name, created_by, created_at, updated_at FROM rooms ORDER BY created_at DESC
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsByUser = `-- name: ListRoomsByUser :many
SELECT id, name, created_by, created_at, updated_at FROM rooms WHERE created_by = ? ORDER BY created_at DESC
`

func (q *Queries) ListRoomsByUser(ctx context.Context, createdBy uint64) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, listRoomsByUser, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :exec
UPDATE rooms SET name = ? WHERE id = ?
`

type UpdateRoomParams struct {
	Name string `db:"name" json:"name"`
	ID   uint64 `db:"id" json:"id"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) error {
	_, err := q.db.ExecContext(ctx, updateRoom, arg.Name, arg.ID)
	return err
}
